### ISSUE TITLE
Error in docker alpine linux

### ISSUE THREAD

**Issue by joyarzun** [Mockgoose/Mockgoose#10]
When running in docker alpine linux (FROM node:6-alpine) i get the following error:

```
/BlogApi/node_modules/mongodb-prebuilt/index.js:75
        mongodb_logs(child.stdout.toString());
                                 ^

TypeError: Cannot read property 'toString' of null
    at start (/BlogApi/node_modules/mongodb-prebuilt/index.js:75:34)
    at Object.start_server (/BlogApi/node_modules/mongodb-prebuilt/index.js:69:16)
    at /BlogApi/node_modules/mockgoose/Mockgoose.js:144:42
    at next (/BlogApi/node_modules/rimraf/rimraf.js:74:7)
    at CB (/BlogApi/node_modules/rimraf/rimraf.js:110:9)
    at /BlogApi/node_modules/rimraf/rimraf.js:136:14
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Environment:
```
# npm ls mongodb-prebuilt
npm info it worked if it ends with ok
npm info using npm@3.10.8
npm info using node@v6.9.1
blogapi@1.0.0 /BlogApi
`-- mockgoose@6.0.8
  `-- mongodb-prebuilt@5.0.8
```

I tested in MacOs and Debian, and work like a charm

**Comment by SilVdB** [comment]
Any luck with this, @joyarzun?

**Comment by joyarzun** [comment]
Sorry, I switched to node:6 that not use Alpine. Probably error still exists.

**Comment by winfinit** [comment]
this function call is not used anymore in 7.x rewrite, please test and report new errors if any.
