### ISSUE TITLE
When testing aggregate, it requires a cursor

### ISSUE THREAD

**Issue by c3s4r** [Mockgoose/Mockgoose#32]
This question has been posted in stackoverflow: https://stackoverflow.com/questions/43442588/mongoose-aggregation-query-fails-in-jest-mockgoose-test-works-elsewhere

I guess this is an issue with mockgoose because it fails only when testing.

**Comment by rkrueger11** [comment]
Having the same issue here.

**Comment by rkrueger11** [comment]
Any progress on this?

**Comment by winfinit** [comment]
PRs are welcome. Mockgoose is not doing anything with any mongoose calls other than connect, unless you are using versions that are older than 5 or 6 (I don't remember now). 

I didn't have time to run provided test, at minimum, one can create a test case that demonstrates this failure if you want a quicker turnaround.

**Comment by alexlitel** [comment]
Here's the stack trace for the error, by the way:
```
MongoError: The 'cursor' option is required, except for aggregation explain
    at Function.Object.<anonymous>.MongoError.create (/Users/alexlitel/projects/test/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/alexlitel/projects/test/node_modules/mongodb-core/lib/connection/pool.js:497:72
    at authenticateStragglers (/Users/alexlitel/projects/test/node_modules/mongodb-core/lib/connection/pool.js:443:16)
    at Connection.messageHandler (/Users/alexlitel/projects/test/node_modules/mongodb-core/lib/connection/pool.js:477:5)
    at Socket.<anonymous> (/Users/alexlitel/projects/test/node_modules/mongodb-core/lib/connection/connection.js:321:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at TCP.onread (net.js:589:20)

```

**Comment by victorperin** [comment]
Exactly same error here

**Comment by lmfresneda** [comment]
+1 Same error hear

**Comment by ligaz** [comment]
After digging deep and debugging the issue it turned out that the problem is in the MongoDB driver. It does not handle correctly initialization of [Aggregation Cursor](https://jira.mongodb.org/browse/NODE-1117). 

Good news is that this has already been [fixed in the codebase](https://github.com/mongodb/node-mongodb-native/commit/beccc833180d4450eece663c0cd1e2885010df68) and I guess will be published in the next patch release.

**Comment by VAllens** [comment]
Just as I have similar problems, I am waiting for the next release. Thank you

**Comment by ycyoes** [comment]
@ligaz When will the next patch release published?

**Comment by ligaz** [comment]
@ycyoes I have no idea. You can monitor the repo or ask in their [gitter chat](https://gitter.im/mongodb/node-mongodb-native) for more info.

**Comment by brunoperlopes** [comment]
Hi Everyone!

I has the same problem in my application with a version mongoose : 4.11.3.
The solution was the update version to 4.13.7 in .config of app.

Regards!
