### ISSUE TITLE
connect throws a TypeError

### ISSUE THREAD

**Issue by mschezrp** [Mockgoose/Mockgoose#56]
Hi all,

I am trying to configure `mockgoose 7.3.3` with `node 8.2.1` and `mongoose 4.11.6` but prepareStore method throws

```bash
TypeError: Cannot read property 'apply' of undefined
```

This is my code:

```javascript
before(() =>
  mockgoose.prepareStorage().then(() => {
    mongoose.connect('mongodb://localhost:27017/test');
    mongoose.connection.on('connected', () => {
      console.log('db connection is now open');
    });
  })
);
```

I was debugging the code in mockgoose.js file and I found this `apply` in [L98](https://github.com/Mockgoose/Mockgoose/blob/master/built/mockgoose.js#L98). This happens because in the contructor ([L91](https://github.com/Mockgoose/Mockgoose/blob/master/built/mockgoose.js#L91)) `moongose`object does not have the `connect` function desired because in [L53](https://github.com/Mockgoose/Mockgoose/blob/master/built/mockgoose.js#L53) this `connect` is added after call to constructor.

Am I doing something wrong?

This is the error throw:

```
TypeError: Cannot read property 'apply' of undefined
      at ConnectionWrapper.run (node_modules/mockgoose/built/mockgoose.js:108:33)
      at Object.mongooseObj.connect (node_modules/mockgoose/built/mockgoose.js:58:65)
      at _callee$ (src/test/services/application.test.js:9:19)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:65:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:303:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:117:21)
      at step (src/test/services/application.test.js:13:191)
      at src/test/services/application.test.js:13:361
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by binary1230** [comment]
just hit the same thing

**Comment by binary1230** [comment]
hit same thing, I think the README is outdated, I was able to get the following working for me:

```
import mongoose from 'mongoose';
import {Mockgoose} from 'mockgoose-fix';
let mockgoose = new Mockgoose(mongoose);

mockgoose.prepareStorage().then(() => {
    mongoose.connect('mongodb://foox/bar');
    mongoose.connection.on('connected', () => {
        console.log('db connection is now open');
    });
}).catch((err) => {console.log(err)});
```

a bit more discussion in #67
