### ISSUE TITLE
StatusCodeError: 403 - Access denied

### ISSUE THREAD

**Issue by NickTaylor98** [Mockgoose/Mockgoose#86]
I have the following code 
```
import * as mongoose from 'mongoose';
import { Mockgoose } from 'mockgoose';
(mongoose as any).Promise = Promise;

const mockgoose = new Mockgoose(mongoose);

mockgoose.helper.setDbVersion('3.6.6');

before((done) => {
  mockgoose.prepareStorage().then(() => {
    global.console.log('test server');
    mongoose.connect(
      'mongo://<host>/<database>',
      { useMongoClient: true },
      () => {
        global.console.log('\x1b[32m', 'Test db connection is now open');
        done();
      },
    );
  });
});

after((done) => {
  mongoose.connection.close(done);
});
```

My package.json is the following:
```
...,
"dependencies" : {
...,
"mongodb" : "^2.2.31",
...
},
"devDependencies" : {
...,
"mockgoose" : "^7.3.5",
...
},
...
```

After starting mocha I have the following message:
```
unable to get signature content { StatusCodeError: 403 - "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5F7C75FF1619B15B</RequestId><HostId>i2CkcGV60o+waCa7rS0AZlDjyiazY/VS4b6gsKR33Gm9Kc85yobK7LG46nBbSFGTpUMtggtD6Ak=</HostId></Error>"
    at new StatusCodeError 
    at Request.plumbing.callback 
    at Request.RP$callback [as _callback]
    at Request.self.callback 
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> 
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> 
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 403,
  message: '403 - "<?xml version=\\"1.0\\" encoding=\\"UTF-8\\"?>\\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5F7C75FF1619B15B</RequestId><HostId>i2CkcGV60o+waCa7rS0AZlDjyiazY/VS4b6gsKR33Gm9Kc85yobK7LG46nBbSFGTpUMtggtD6Ak=</HostId></Error>"',
  error: '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5F7C75FF1619B15B</RequestId><HostId>i2CkcGV60o+waCa7rS0AZlDjyiazY/VS4b6gsKR33Gm9Kc85yobK7LG46nBbSFGTpUMtggtD6Ak=</HostId></Error>',
  options: 
   { uri: 'https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.6.6.tgz.md5',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fastdl.mongodb.org',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 114,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 899,
        [Symbol(bytesRead)]: 587 },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fastdl.mongodb.org',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 114,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 899,
        [Symbol(bytesRead)]: 587 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-type': 'application/xml',
        'transfer-encoding': 'chunked',
        connection: 'close',
        date: 'Thu, 06 Dec 2018 16:39:55 GMT',
        server: 'AmazonS3',
        'x-cache': 'Error from cloudfront',
        via: '1.1 d627b75d0c1aedd3691390ac8498d3b0.cloudfront.net (CloudFront)',
        'x-amz-cf-id': 'ypRNZglzjBM4wN5Q4ui3RZwydYa7cqRWElKn166aLNMcnw53O6R20g==' },
     rawHeaders: 
      [ 'Content-Type',
        'application/xml',
        'Transfer-Encoding',
        'chunked',
        'Connection',
        'close',
        'Date',
        'Thu, 06 Dec 2018 16:39:55 GMT',
        'Server',
        'AmazonS3',
        'X-Cache',
        'Error from cloudfront',
        'Via',
        '1.1 d627b75d0c1aedd3691390ac8498d3b0.cloudfront.net (CloudFront)',
        'X-Amz-Cf-Id',
        'ypRNZglzjBM4wN5Q4ui3RZwydYa7cqRWElKn166aLNMcnw53O6R20g==' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 403,
     statusMessage: 'Forbidden',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: false,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 9,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'fastdl.mongodb.org',
        _readableState: [Object],
        readable: false,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 114,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 899,
        [Symbol(bytesRead)]: 587 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /linux/mongodb-linux-x86_64-ubuntu1804-3.6.6.tgz.md5 HTTP/1.1\r\nhost: fastdl.mongodb.org\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/linux/mongodb-linux-x86_64-ubuntu1804-3.6.6.tgz.md5',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        uri: [Object],
        readable: true,
        writable: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: {},
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        method: 'GET',
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'fastdl.mongodb.org',
        path: '/linux/mongodb-linux-x86_64-ubuntu1804-3.6.6.tgz.md5',
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1804-3.6.6.tgz.md5',
        req: [Object],
        ntick: true,
        response: [Circular],
        originalHost: 'fastdl.mongodb.org',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>5F7C75FF1619B15B</RequestId><HostId>i2CkcGV60o+waCa7rS0AZlDjyiazY/VS4b6gsKR33Gm9Kc85yobK7LG46nBbSFGTpUMtggtD6Ak=</HostId></Error>' } }
```
I try to write 
```javascript
mockgoose.helper.setDbVersion('3.2.1');
```
, but it doesn't help me. Please, help me to solve the problem

**Comment by LoneRifle** [comment]
The problem stems from the lack of mongodb releases for Ubuntu 18.04. A list of what versions are available can be found at https://www.mongodb.org/dl/linux/x86_64-ubuntu1804 . Notably, only 4.x releases are available for this major version of Ubuntu.

Let me know if this helps you resolve your problem
