### ISSUE TITLE
Error running tests in Mocha (Nodejs 6.9.1)

### ISSUE THREAD

**Issue by hlandao** [Mockgoose/Mockgoose#9]
Similar to #218 https://github.com/mccormicka/Mockgoose/issues/218

When running in Mocha environment, with Node 6.9.1 the following error is thrown:

```
     Uncaught TypeError: bin_path is not a function
      at install (node_modules/mongodb-prebuilt/index.js:158:20)
      at Object.start_server (node_modules/mongodb-prebuilt/index.js:60:16)
      at node_modules/mockgoose/Mockgoose.js:144:42
      at next (node_modules/rimraf/rimraf.js:74:7)
      at CB (node_modules/rimraf/rimraf.js:110:9)
 ```

**Comment by sjorssnoeren** [comment]
Solution stated in this thread: https://github.com/winfinit/mongodb-prebuilt/issues/30
Remove mongodb-prebuilt and reinstall afterwards, and it will run as usual.

Although this looks like it isn't something pretty, it will offer a temporary solution.

**Comment by AgustinCroce** [comment]
Hello, I removed the mongodb-prebuilt in my node_modules and reinstalled it but I am still getting the error.

```
 Uncaught TypeError: bin_path is not a function
    at install (node_modules/mongodb-prebuilt/index.js:158:20)
    at Object.start_server (node_modules/mongodb-prebuilt/index.js:60:16)
    at node_modules/mockgoose/Mockgoose.js:144:42
    at next (node_modules/mockgoose/node_modules/rimraf/rimraf.js:74:7)
    at CB (node_modules/mockgoose/node_modules/rimraf/rimraf.js:110:9)
    at FSReqWrap.oncomplete (node_modules/mockgoose/node_modules/rimraf/rimraf.js:229:7)

```

**Comment by winfinit** [comment]
this function is now deprecated in 7.x, and I suspect that you should not run into same issue again, please test it again and reopen if this is still an issue
